# Generated by Django 6.0.5 on 2026-05-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('accent', models.CharField(default='#3a3a3a', max_length=7)),
                ('accent_soft', models.CharField(default='#ece8e1', max_length=7)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_lesson_number', models.PositiveIntegerField()),
                ('order_in_unit', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=400)),
                ('summary', models.CharField(blank=True, max_length=600)),
                ('content', models.TextField(blank=True, help_text='Markdown. Footnotes supported.')),
                ('slug', models.SlugField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_lessons', to='courses.course')),
            ],
            options={
                'ordering': ['course_lesson_number', 'course__order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course')),
            ],
            options={
                'ordering': ['course__order', 'order'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'course_lesson_number'), ('course', 'slug')},
        ),
    ]
