# Generated by Django 6.0.6 on 2026-06-29 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('quote', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='yellow', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='courses.lesson')),
            ],
            options={
                'ordering': ['start_offset', 'id'],
            },
        ),
    ]
