# Generated by Django 6.0.6 on 2026-07-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_lesson_number',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
